# Generated by Django 4.2.5 on 2023-10-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'EASY'), ('medium', 'MEDIUM'), ('hard', 'HARD')], default='easy', max_length=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
